title: All Problems
description: Problems
author: Kerem Demirtürk
github: https://github.com/keremdemirtrk
about: I'm studying at KTU Computer Engineering
disqus_shortname: Problems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/kerem.demirturk1"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/keremdemirtrk/"
    - icon: fa-github
      link: "https://github.com/keremdemirtrk"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://keremdemirtrk.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
